version: '3.8'

services:
  systempix_db:
    image: 'mysql:8.1'
    container_name: systempix_db
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=mydb
      - MYSQL_PASSWORD=4110Isabela
      - MYSQL_ROOT_PASSWORD=4110Isabela
    networks:
      - systempix
    volumes:
      - systempix:/var/lib/systempix
    ports:
      - 3307:3306

networks:
  systempix:
    driver: bridge

volumes:
  systempix: